#本地模式：h2数据库、内存缓存，因此不需要其他基础设施，可以直接运行

#全局datasource配置,默认使用h2数据库
spring:
  datasource:                            #初始化sql配置
    initialization-mode: always
    continue-on-error: false                        #在初始化数据库时，遇到错误是否继续，默认false
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/db/diamondsample
    platform: h2
    username: sa
    password: sa
    data: "classpath:/init/h2data.sql"      #初始化sql配置
    schema: "classpath:/init/h2schema.sql"  #初始化sql配置
    sql-script-encoding: UTF-8
  h2:
    console:
      settings:
          web-allow-others: true #生产环境设置为false，关闭控制台
      path: /h2-console
      enabled: true #生产环境设置为false，关闭控制台

# 日志配置
logging:
  level:
    org.springframework.web: debug
    com.hoioy.diamond: debug

# swagger2是否开启
knife4j:
  # 开启增强配置
  enable: true
  # 部署到生产环境时，建议设置为true开启生产环境屏蔽
  production: false

---
# 统一认证配置
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://oauth2.taiji.com.cn/.well-known/jwks.json  #向OAuth2 请求密钥的接口地址
