---
#全局datasource配置
spring:
  datasource:                            #初始化sql配置
    initialization-mode: never
    continue-on-error: true                        #在初始化数据库时，遇到错误是否继续，默认false
    test-on-borrow: false                           #当从连接池借用连接时，是否测试该连接.
    test-while-idle: true                           #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 3600000    #数据库连接时间

---
#mysql配置
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"     # mysql 8时候配置
    url: "jdbc:mysql://117.78.11.219:3306/diamondtest?serverTimezone=GMT%2B8&amp&characterEncoding=utf-8&useSSL=false"  #  mysql 8时候配置
    data: "classpath:/init/mysqldata.sql"      #初始化sql配置
    schema: "classpath:/init/schemamysql.sql"  #初始化sql配置,使用mybatis时候可以打开,
    username: root
    password: Jiayinxiaochengxu@123
    data-username: root
    data-password: Jiayinxiaochengxu@123
---
# redis配置
spring:
  lettuce:
    pool:
      max-active: 500
      max-idle: 500
      max-wait: -1
      min-idle: 10
  redis:
    database: 4
    host: 117.78.11.219
    port: 6379
    timeout: 3000

# 日志配置
logging:
  level:
    org.springframework.web: debug
    com.hoioy.diamond: debug

# swagger2是否开启
swagger2:
  enable: true

---
# TODO mybatis配置，如果使用jpa可以删除
mybatis-plus:
  #扫描多个模块下的mapper.xml
  mapper-locations: classpath*:mapper/**/*.xml
  #  type-aliases-package: com.hoioy.diamond.log.domain,com.hoioy.diamond.sys.domain     #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: com.hoioy.diamond.log.domain,com.hoioy.diamond.sys.domain,com.hoioy.jiayin.domain    #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  #type-aliases-super-type: java.lang.Object     #该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  global-config:
    db-config:
      logic-delete-field: flag             #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 0                # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1            # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true     #是否开启自动驼峰命名规则（camel case）映射,如果明明规范不需要使用@TableField
    cache-enabled: false
    call-setters-on-nulls: true


# HTTPS的密钥配置
server:
  ssl:
    key-store: classpath:www.hoioy.com.jks
    key-store-password: 123456
    keyStoreType: JKS